on:
  - pull_request
  - push
  - workflow_dispatch

name: CI

jobs:
  run:
    name: Tests

    strategy:
      matrix:
        operating-system: [ ubuntu-latest, macos-latest ]
        php-versions: [ '8.2', '8.3' ]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Run Benchmarks
        run: make benchmark

      - name: Note Results
        run: cat benchmark.log >> $GITHUB_STEP_SUMMARY
